language: node_js
sudo: false

node_js:
  - "10"

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run dev:weapp
        - npm run build:weapp
